apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-clickhouse
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 5.3.1
    chart: clickhouse
    helm:
#      parameters:
#        - name: someParameter
#          value: someValue
      valuesObject:
        auth:
          username: csi
          password: iceberg
        global:
          storageClass: "ceph-block"
        ingress:
          ingressClassName: nginx
          enabled: true
          hostname: csi4142-clickhouse.mershab.xyz
  destination:
    name: loft-new-project-vcluster-csi4142-cluster
    namespace: clickhouse
  syncPolicy:
    automated: 
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - priority=8

