apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-metabase
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://pmint93.github.io/helm-charts
    targetRevision: 2.11.0
    chart: metabase
    helm:
#      parameters:
#        - name: someParameter
#          value: someValue
      valuesObject:
        pluginsDirectory: /plugins
        extraVolumes:
          - name: plugins
        extraVolumeMounts:
          - name: plugins
            mountPath: /plugins
            readOnly: false

        extraInitContainers:
          - name: download-modules
            image: "curlimages/curl:7.70.0"
            imagePullPolicy: "IfNotPresent"
            volumeMounts:
              - name: plugins
                mountPath: /plugins
            workingDir: /plugins
            command:
              - "/bin/sh"
              - "-ec"
              - |
                curl -Lso /plugins/clickhouse.metabase-driver.jar \
                          https://github.com/ClickHouse/metabase-clickhouse-driver/releases/download/1.4.0/clickhouse.metabase-driver.jar

        ingress:
          className: nginx
          enabled: true
          hosts:
            - csi4142-metabase.mershab.xyz
  destination:
    name: loft-new-project-vcluster-csi4142-cluster
    namespace: metabase
  syncPolicy:
    automated: 
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - priority=8

